name: Schedule Workflow Test

on: 
  workflow_dispatch: 
  schedule:
    - cron: "8 1 * * *"
      

jobs:
  interview:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule Test
        run: echo "I've done Test"
