name: Schedule Workflow Test

on: 
  schedule:
    - cron: "55 19 * * *"
      workflow_dispetch

jobs:
  interview:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule Test
        run: echo "I've done Test"
